# Python lasy plugins ########

# [[plugins]]
# repo = 'scrooloose/syntastic'
# on_ft = ['python']
# hook_add = '''
#     let g:syntastic_python_checkers = ['pydocstyle', 'pycodestyle', 'pyflakes']
#     '''

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']
hook_add = '''
    let g:jedi#auto_initialization = 0
    let g:jedi#auto_vim_configuration = 0
    let g:jedi#smart_auto_mappings = 0
    let g:jedi#completions_enabled = 0
    let g:jedi#force_py_version = 3
    let g:jedi#popup_select_first = 0
    let g:jedi#popup_on_dot = 0
    let g:jedi#rename_command = "<leader>R"
    let g:jedi#goto_command = "<Leader>d"
    let g:jedi#documentation_command = "K"
    autocmd FileType python setlocal completeopt-=preview
    '''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']
on_i = 1

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

# [[plugins]]
# repo = 'w0rp/ale'
# on_ft = ['python']
# hook_add = '''
#     " エラー行に表示するマーク
#     let g:ale_sign_error = '⨉'
#     let g:ale_sign_warning = '⚠'
#     " エラー行にカーソルをあわせた際に表示されるメッセージフォーマット
#     let g:ale_echo_mlg_format = '[%linter%] %s [%severity%]'
#     " エラー表示の列を常時表示
#     let g:ale_sign_column_always = 1
#     
#     " ファイルを開いlときにlint実行
#     let g:ale_lint_on_enter = 1
#     " ファイルを保存したときにlint実行
#     let g:ale_lint_on_save = 1
#     " 編集中のlintはしない
#     let g:ale_lint_on_text_changed = 'never'
#     
#     " lint結果をロケーションリストとQuickFixには表示しない
#     " 出てると結構うざいしQuickFixを書き換えられるのは困る
#     "let g:ale_set_loclist = 0
#     "let g:ale_set_quickfix = 0
#     "let g:ale_open_list = 0
#     "let g:ale_keep_list_window_open = 0
#     
#     " 有効にするlinter
#     let g:ale_linters = {
#     \   'python': ['flake8'],
#     \}
# 
#     " 各ツールをFixerとして登録
#     let g:ale_fixers = {
#     \ 'python': ['autopep8', 'black', 'isort'],
#     \ }
#     
#     " 各ツールの実行オプションを変更してPythonパスを固定
#     "let g:ale_python_flake8_executable = g:python3_host_prog
#     "let g:ale_python_flake8_options = '-m flake8'
#     "let g:ale_python_autopep8_executable = g:python3_host_prog
#     "let g:ale_python_autopep8_options = '-m autopep8'
#     "let g:ale_python_isort_executable = g:python3_host_prog
#     "let g:ale_python_isort_options = '-m isort'
#     "let g:ale_python_black_executable = g:python3_host_prog
#     "let g:ale_python_black_options = '-m black'
# 
#     " エラー行にジャンプ
#     nmap <silent> <C-k> <Plug>(ale_previous_wrap)
#     nmap <silent> <C-j> <Plug>(ale_next_wrap)
#     '''

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'

