[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
    " Set fzf command path
    set runtimepath+=/usr/local/opt/fzf
    " Keybind
    nnoremap [fzf] <Nop>
    nmap <C-f> [fzf]
    nmap [fzf]<C-p> :Files<CR>
    nmap [fzf]<C-g> :GFiles?<CR>
    nmap [fzf]<C-f> :Buffers<CR>
    nmap [fzf]<C-t> :BTags<CR>
    nmap [fzf]<C-d> :Files ~/.dotfiles<CR>
    nmap [fzf]<C-h> :History<CR>
    " Selection keybind
    let g:fzf_action = {
        \ 'ctrl-t': 'tab split',
        \ 'ctrl-k': 'split',
        \ 'ctrl-h': 'vsplit' }
    " Files with preview window
    command! -bang -nargs=? -complete=dir Files
        \ call fzf#vim#files(<q-args>, fzf#vim#with_preview(), <bang>0)
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#auto_complete_delay = 0
    let g:deoplete#auto_complete_start_length = 1
    let g:deoplete#enable_camel_case = 0
    let g:deoplete#enable_ignore_case = 0
    let g:deoplete#enable_refresh_always = 0
    let g:deoplete#enable_smart_case = 1
    let g:deoplete#file#enable_buffer_path = 1
    let g:deoplete#max_list = 10
    inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \   "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
    '''

[[plugins]]
repo = 'Shougo/neosnippet'
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    let NERDTreeWinPos='left'
    let g:nerdtreewinsize=50        " 表示幅
    let g:NERDTreeMapUpdir=''       " 親ディレクトリへ移動
    let g:NERDTreeShowHidden=1      " 隠しファイルを表示
    let g:NERDTreeIgnore=['\.git$', '\.clean$', '\.swp$', '\.bak$', '\~$']
    '''

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
    let g:tagbar_left = 1
    let g:tagbar_vertical = 25
    '''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    let g:quickrun_config = {
        \ '_' : {
            \ 'runner' : 'vimproc',
            \ 'runner/vimproc/updatetime' : 60,
            \ 'outputter' : 'error',
            \ 'outputter/error/success' : 'buffer',
            \ 'outputter/error/error'   : 'quickfix',
            \ 'outputter/buffer/split' : ':botright 8sp',
        \ }
    \}
    '''

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']

[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = '''
    let g:cheatsheet#cheat_file = '~/.dotfiles/doc/vim_cheatsheet.md'
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
    vmap <CR> <Plug>(EasyAlign)
'''

