[[plugins]]
repo = 'Shougo/dein.vim'

# 非同期処理プラグイン
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/denite.nvim'

# 補完プラグイン
[[plugins]]
repo = 'Shougo/deoplete.nvim'
# on_event = 'InsertCharPre'
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#auto_complete_delay = 0
    let g:deoplete#auto_complete_start_length = 1
    let g:deoplete#enable_camel_case = 0
    let g:deoplete#enable_ignore_case = 0
    let g:deoplete#enable_refresh_always = 0
    let g:deoplete#enable_smart_case = 1
    let g:deoplete#file#enable_buffer_path = 1
    let g:deoplete#max_list = 10
    " inoremap <expr><tab> pumvisible() ? "\<C-n>" :
    "     \ neosnippet#expandable_or_jumpable() ?
    "    \   "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
    '''
on_i = 1 

# file viewer
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    " 表示幅
    let g:nerdtreewinsize=50
    " ブックマークを表示
    let g:NERDTreeShowBookmarks=1
    " 親ディレクトリへ移動
    let g:NERDTreeMapUpdir=''
    " ファイルの開き方
    let g:NERDTreeMapOpenSplit='<C-j>'
    let g:NERDTreeMapOpenVSplit='<C-l>'
    " ファイルを開いたらNERDTreeを閉じる
    let g:NERDTreeQuitOnOpen=1
    " 隠しファイルを表示
    let g:NERDTreeShowHidden=1
    " 非表示ファイル
    let g:NERDTreeIgnore=['\.git$', '\.clean$', '\.swp$', '\.bak$', '\~$']
'''

# カーソル位置のコンテキストに合わせてftを切り替える
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

# カーソル位置のコンテキストのftを判定
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# vim-airline
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    " let g:airline_powerline_fonts = 1
    " set guifont=Ricty\ Regular\ for\ Powerline:h14
    " let g:Powerline_symbols = 'fancy'
    set t_Co=256

    let g:airline_section_a = airline#section#create(['mode','','branch'])
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#show_buffers = 0
    let g:airline#extensions#tabline#tab_nr_type = 1
    let g:airline#extensions#tabline#fnamemod = ':t' 
   
    " let g:airline_left_sep = '⮀'
    " let g:airline_right_sep = '⮂'
    " let g:airline_linecolumn_prefix = '⭡'
    " let g:airline_branch_prefix = '⭠'
    " let g:airline#extensions#tabline#left_sep = '⮀'
    " let g:airline#extensions#tabline#left_alt_sep = '⮀'

    let g:airline#extensions#tabline#enabled = 1
    '''

# vim-airline-theme
[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
    let g:airline_theme='onedark'
    '''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:indentLine_color_term = 111
    let g:indentLine_color_gui = '#708090'
    let g:indentLine_char = "|"
    '''

[[plugins]]
repo = 'vim-scripts/vectorscript.vim'

