[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tpope/vim-surround'

# vim-airline
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    " let g:airline_powerline_fonts = 1
    " set guifont=Ricty\ Regular\ for\ Powerline:h14
    " let g:Powerline_symbols = 'fancy'
    set t_Co=256
    let g:airline_section_a = airline#section#create(['mode','','branch'])
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#show_buffers = 0
    let g:airline#extensions#tabline#tab_nr_type = 1
    let g:airline#extensions#tabline#fnamemod = ':t'
    " let g:airline_left_sep = '⮀'
    " let g:airline_right_sep = '⮂'
    " let g:airline_linecolumn_prefix = '⭡'
    " let g:airline_branch_prefix = '⭠'
    " let g:airline#extensions#tabline#left_sep = '⮀'
    " let g:airline#extensions#tabline#left_alt_sep = '⮀'
    let g:airline#extensions#tabline#enabled = 1
    '''

# vim-airline-theme
[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
    colorscheme onedark
    let g:airline_theme='onedark'
    '''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:indentLine_color_term = 111
    let g:indentLine_color_gui = '#708090'
    let g:indentLine_char = "|"
    '''

