# TOML lazy plugins ########

# syntacs
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# カーソル位置のコンテキストに合わせてftを切り替える
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_ft = 'toml'

# カーソル位置のコンテキストのftを判定
[[plugins]]
repo = 'Shougo/context_filetype.vim'
on_ft = 'toml'
