[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    set t_Co=256
    let g:airline_section_a = airline#section#create(['mode','','branch'])
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#formatter = 'unique_tail_improved'
    let g:airline#extensions#tabline#fnamemod = ':t'
    let g:airline#extensions#tabline#fnamecollapse=0
    let g:airline#extensions#tabline#fnametruncate=0
    let g:airline#extensions#tabline#show_buffers = 0
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
    let g:airline_theme = 'simple'
'''

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
    colorscheme molokai 
'''

[[plugins]]
repo = 'yggdroot/indentline'
hook_add = '''
    let g:indentline_color_term = 111
    let g:indentline_color_gui = '#708090'
    let g:indentline_char = "|"
    '''

[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = '''
    let g:cheatsheet#cheat_file = '~/.dotfiles/vim_cheatsheet.md'
'''


[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

