[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    set t_Co=256
    let g:airline_section_a = airline#section#create(['mode','','branch'])
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#formatter = 'unique_tail_improved'
    let g:airline#extensions#tabline#show_buffers = 0
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
    let g:airline_theme = 'deus'
'''

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
    " Pair caret color
    autocmd ColorScheme * highlight MatchParen ctermbg=gray
    " Caret bar color
    autocmd ColorScheme * highlight Normal ctermbg=none
    autocmd ColorScheme * highlight LineNr ctermbg=none
    " Selected color
    autocmd ColorScheme * highlight Visual ctermbg=darkblue
    colorscheme molokai 
'''

[[plugins]]
repo = 'yggdroot/indentline'
hook_add = '''
    let g:indentline_color_term = 111
    let g:indentline_color_gui = '#708090'
    let g:indentline_char = "|"
    '''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    set signcolumn=yes
    set updatetime=50
    let g:gitgutter_sign_added = '∙'
    let g:gitgutter_sign_modified = '∙'
    let g:gitgutter_sign_removed = '∙'
    let g:gitgutter_sign_modified_removed = '∙'
'''

